# Site settings
title: Peilin's Blog    				  	#你博客的标题
SEOTitle: Peilin's You Blog    	 #显示在浏览器上搜索的时候显示的标题
header-img: img/avatar-g.jpg  	#显示在首页的背景图片
email: perry971221@gmail.com	
description: "Welcome To My Blog"  			 #网站介绍
keyword: "BY, BY Blog, iOS, Apple, iPhone" #关键词
url: "https://137thphxx.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写


# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: "Test"
sidebar-avatar:/img/avatar-m.JPG      # 你的个人头像 这里你可以改成我在img文件夹中的两张备用照片 img/avatar-m 或 avatar-g

# SNS settings
RSS: false
github_username:    137thphxx
facebook_username:  Peilin Wu
